# Generated by Django 4.2.5 on 2023-10-21 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
    ]
